project:
  title: "ccrquartotest"
format:
  pdf:
    documentclass: ccs
    include-in-header:
      - preamble.tex
    template-partials:
      - partials/title.tex
      - partials/before-body.tex
pdf-engine: pdflatex

editor: visual
